name: Deploy Account Service to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Azure CLI - ACR Login
        run: |
          az acr login --name depaulacr


      - name: Build and Push Docker image to ACR
        run: |
          docker build -t depaulacr.azurecr.io/app:latest .
          docker push depaulacr.azurecr.io/app:latest


      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group depaulRG --name depaulaks --overwrite-existing


      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
